/* eslint-disable @typescript-eslint/no-require-imports -- isolated PostgreSQL integration. */
const test = require('node:test');
const assert = require('node:assert/strict');
const { NextRequest } = require('next/server');
const createFixture = require('./helpers/ledger-sql-fixture.cjs');
const modulePath = process.env.LEDGER_TASKS_PGLITE_MODULE;
const uuid = n => `00000000-0000-4000-8000-${String(n).padStart(12, '0')}`;
test('saved correction resolves durable IDs, previews changes, updates once, and refreshes stale approval', { skip: !modulePath }, async t => {
  const f = await createFixture(modulePath); t.after(f.close);
  const category = { id: uuid(1), name: '餐饮', type: 'expense' }, member = { id: uuid(2), name: '本人' };
  await f.db.query("INSERT INTO categories(id,user_id,name,type) VALUES($1,'owner','餐饮','expense')", [category.id]);
  await f.db.query("INSERT INTO members(id,user_id,name) VALUES($1,'owner','本人')", [member.id]);
  const draft = { id: uuid(3), type: 'expense', amount_cents: 2000, category_id: category.id, member_id: member.id, transaction_date: '2026-10-09', description: '吃饭', payment_method: null, note: '' };
  const batch = { batch_id: uuid(4), status: 'saved', drafts: [draft] };
  const confirmed = await f.load('app/api/assistant/confirm/route.ts').POST(new NextRequest('http://test/api/assistant/confirm', { method: 'POST', body: JSON.stringify({ batch_id: batch.batch_id, drafts: [draft] }) }));
  assert.equal(confirmed.status, 200);
  const [transactionId] = (await confirmed.json()).ids;
  await f.db.query("INSERT INTO transactions(id,user_id,type,amount,category_id,member_id,transaction_date,description) VALUES($1,'owner','expense',20,$2,$3,'2026-10-09','吃饭')", [uuid(5), category.id, member.id]);
  const helpers = f.load('lib/assistant-saved-records.ts'), server = f.load('lib/assistant-command-server.ts');
  const raw = { action: 'edit', reply: '修改金额', drafts: [], query: null, edit: { batch_id: batch.batch_id, edits: [{ draft_id: draft.id, amount_cents: 2200 }] } };
  const normalized = await helpers.normalizeSavedRecordEdit('owner', raw, batch, [category], [member]);
  assert.equal(normalized.action, 'manage');
  assert.equal(normalized.command.ids[0], transactionId);
  assert.deepEqual(JSON.parse(normalized.command.values_json), { amount: 22 });
  await assert.rejects(helpers.normalizeSavedRecordEdit('foreign', raw, batch, [category], [member]), /不存在或已撤销/);
  const plan = await server.prepareLedgerCommand('owner', uuid(6), normalized.command);
  assert.equal(plan.approval.preview.approveLabel, '确认修改');
  assert.equal(plan.approval.preview.records[0].rows[0].value, '¥20.00 → ¥22.00');
  const amount = async () => Number((await f.db.query('SELECT amount FROM transactions WHERE id=$1', [transactionId])).rows[0].amount);
  assert.equal(await amount(), 20);
  const result = await server.decideAssistantAction('owner', plan.approval.id, 'approve');
  assert.equal(result.status, 'succeeded', result.text);
  assert.equal(result.transaction_updates[0].amount_cents, 2200);
  assert.equal(result.transaction_updates[0].batch_id, batch.batch_id);
  assert.equal(result.transaction_updates[0].draft_id, draft.id);
  assert.equal(result.transaction_updates[0].transaction_date, '2026-10-09');
  await server.decideAssistantAction('owner', plan.approval.id, 'approve');
  assert.equal(await amount(), 22);
  const other = (await f.db.query('SELECT amount FROM transactions WHERE id=$1', [uuid(5)])).rows[0];
  assert.equal(Number(other.amount), 20);
  assert.equal((await f.db.query('SELECT * FROM transactions')).rows.length, 2);
  const next = await server.prepareLedgerCommand('owner', uuid(6), { ...normalized.command, values_json: '{"amount":25}' });
  await f.db.query('UPDATE transactions SET amount=23 WHERE id=$1', [transactionId]);
  const conflict = await server.decideAssistantAction('owner', next.approval.id, 'approve');
  assert.equal(conflict.status, 'failed');
  assert.equal(conflict.completed, 0);
  assert.equal(await amount(), 23);
  assert.equal(conflict.replacement_approval.preview.records[0].rows[0].value, '¥23.00 → ¥25.00');
  const fresh = await server.decideAssistantAction('owner', conflict.replacement_approval.id, 'approve');
  assert.equal(fresh.status, 'succeeded');
  assert.equal(await amount(), 25);
  const oldRead = await server.getAssistantAction('owner', plan.approval.id);
  assert.equal(oldRead.transaction_updates[0].amount_cents, 2500, 'reading an old receipt must not roll the card back');
  const original = (await f.db.query('SELECT draft_snapshot FROM assistant_batches WHERE user_id=$1 AND id=$2', ['owner', batch.batch_id])).rows[0].draft_snapshot;
  assert.equal(original[0].amount_cents, 2000, 'original undo snapshot is immutable');
});
